#!/usr/bin/env python3
"""
generate_logo_from_png.py

Admin-only utility -- NOT invoked by .github/workflows/aggregate-layout.yml
or import-submission.yml, run manually whenever a new/updated logo needs
to be added to logos/. Digitizes a source PNG into a DRC-safe M2
dot-matrix GDS cell suitable for logos/ (see info.yaml's logo.* section
and map.yaml, consumed by scripts/aggregate_gds.py's
resolve_logo_path_for_position()/get_or_load_logo_cell()).

Background (this session): reviewing the aggregation-side logo scheme
found that the existing logos/OpenSUSI_LOGO.gds / FFG_LOGO.gds are both
drawn on layer 13/0, which TR-1um.lyp identifies as **M1** (a real,
DRC-checked metal layer, not an inert marking layer) -- and as solid,
touching 2.0x2.0um pixel blocks (no gap between adjacent ON cells).
aggregate_gds.py places these directly onto each user's own finished
chip at fixed absolute coordinates with no collision/keepout check
against that chip's own M1 geometry, which is a real short/DRC risk.

Per user instruction this session, NEW logo art generated by this
script targets **M2** instead (still real DRC-checked metal, but at
least a different layer than most projects' densest M1 wiring), with
an explicit dot pitch/size: **3.0um dot, 2.0um space**. Each digitized
ON grid-cell is rendered as an ISOLATED 3.0x3.0um M2 square, centered
in a 5.0um pitch cell (PITCH = M2 Wmin(3.0) + Smin(2.0), 1.0um margin
per side) -- exactly the technique established in this session's
TR-1um_Async_I2C/script/place_opensusi_logo_dots.py for the on-chip
OpenSUSI logo:
  - an isolated dot is exactly 3.0um wide -- legal, since a DRC width
    violation is defined as STRICTLY less than Wmin (M2.W1: M2 Wmin <
    3.0 in this PDK's own run.drc), so exactly-Wmin is not a violation.
  - two orthogonally-adjacent ON cells leave an exact 2.0um gap
    ((5.0-3.0), split 1.0um/side) -- legal by the same "meets Smin
    exactly" reasoning (M2.S1: M2 Smin < 2.0).
  - two diagonally-adjacent ON cells clear by sqrt(2^2+2^2)=2.83um,
    safely above Smin -- no diagonal-touch patch needed (unlike a
    merged-block rendering, where a diagonal-only touch is a zero-
    width/coincident-corner DRC ambiguity).
This does NOT change the existing logos/OpenSUSI_LOGO.gds /
FFG_LOGO.gds files or the M1-vs-M2 collision-risk issue itself (a
separate, not-yet-decided question) -- it only adds the capability to
generate new M2-based logo art the same way the chip-side logo was
fixed.

Usage:
    python3 scripts/generate_logo_from_png.py <input.png> <output.gds> [cell_name]

Example (this session):
    python3 scripts/generate_logo_from_png.py \\
        ../uploads/OpenSUSI_LOGO_200x200.png \\
        logos/OpenSUSI_LOGO_dots.gds

The output cell name defaults to the output file's stem if not given.
Fails loudly (SystemExit) if the digitized footprint exceeds
info.yaml's logo.bbox (320 x 160um) or if the self-check
(width_check/space_check against M2 Wmin/Smin) finds any violation --
never silently writes a bad logo.
"""
import sys
from pathlib import Path

import numpy as np
from PIL import Image
import klayout.db as db

M2_LAYER = (20, 0)
M2_WMIN = 3.0
M2_SMIN = 2.0
PITCH = M2_WMIN + M2_SMIN      # 5.0um
DOT = M2_WMIN                  # 3.0um -- user instruction: "3um dot"
MARGIN = (PITCH - DOT) / 2.0   # 1.0um -- user instruction: "2um space" (2x1.0)

# info.yaml: logo.bbox -- must not be exceeded (ensure_bbox_within_limit
# in aggregate_gds.py enforces this at aggregate time too; checked here
# up front so a bad logo is never written to logos/ in the first place).
BBOX_X_MAX = 320.0
BBOX_Y_MAX = 160.0

WHITE_THRESHOLD = 245
ALPHA_THRESHOLD = 10
CROP_MARGIN_FRACTION = 0.02  # 2% of the ink bbox's larger dimension


def load_ink_mask(png_path: Path) -> np.ndarray:
    im = Image.open(png_path).convert("RGBA")
    arr = np.array(im)
    alpha = arr[:, :, 3]
    rgb = arr[:, :, :3].astype(int)
    white_mask = np.all(rgb > WHITE_THRESHOLD, axis=2)
    ink = (~white_mask) & (alpha > ALPHA_THRESHOLD)

    if not ink.any():
        raise RuntimeError(f"no ink pixels found in {png_path}")

    return ink


def compute_grid_size(ink: np.ndarray) -> tuple[int, int]:
    """Real ink aspect ratio (measured, not assumed from a thumbnail),
    fit into the bbox at the fixed PITCH -- height-bound first (matches
    a square/tall source like an icon-only logo), falling back to
    width-bound if the aspect ratio needs the full 320um budget."""
    ys, xs = np.where(ink)
    ink_w = xs.max() - xs.min() + 1
    ink_h = ys.max() - ys.min() + 1
    aspect = ink_w / ink_h

    rows = int(BBOX_Y_MAX // PITCH)
    cols = max(1, int(round(rows * aspect)))

    if cols * PITCH > BBOX_X_MAX:
        cols = int(BBOX_X_MAX // PITCH)
        rows = max(1, int(round(cols / aspect)))

    return cols, rows


def digitize(ink: np.ndarray, grid_cols: int, grid_rows: int) -> np.ndarray:
    ys, xs = np.where(ink)
    x0, x1, y0, y1 = xs.min(), xs.max(), ys.min(), ys.max()
    margin = max(2, int(CROP_MARGIN_FRACTION * max(x1 - x0, y1 - y0)))
    x0 = max(0, x0 - margin)
    y0 = max(0, y0 - margin)
    x1 = min(ink.shape[1] - 1, x1 + margin)
    y1 = min(ink.shape[0] - 1, y1 + margin)
    crop = ink[y0:y1 + 1, x0:x1 + 1]

    crop_img = Image.fromarray((crop * 255).astype(np.uint8))
    small = crop_img.resize((grid_cols, grid_rows), Image.BOX)
    grid_on = (np.array(small).astype(float) / 255.0) >= 0.5
    return grid_on


def build_logo_cell(grid_on: np.ndarray, cell_name: str):
    ly = db.Layout()
    ly.dbu = 0.001
    cell = ly.create_cell(cell_name)
    li_m2 = ly.layer(*M2_LAYER)
    dbu = ly.dbu

    rows, cols = grid_on.shape

    region = db.Region()
    for j in range(rows):
        gds_j = rows - 1 - j  # flip vertically: image row 0 (top) -> highest Y
        for i in range(cols):
            if not grid_on[j, i]:
                continue
            x0 = i * PITCH + MARGIN
            x1 = x0 + DOT
            y0 = gds_j * PITCH + MARGIN
            y1 = y0 + DOT
            box = db.DBox(x0, y0, x1, y1).to_itype(dbu)
            region.insert(box)

    # Center the ACTUAL ink bbox on the origin. info.yaml documents
    # logo.bbox as "expected logo bbox (centered origin)", and
    # aggregate_gds.py's outer-edge placement formula
    # (build_user_wrapper_cell) assumes each logo's own cell.bbox() is
    # symmetric about (0,0). Before this fix, dots were placed starting
    # at the GRID's nominal origin (cols*PITCH x rows*PITCH), which is
    # only centered on the ink when ink happens to fill every edge row
    # and column -- otherwise the real (tighter) ink bbox ends up
    # off-center. Re-center on the real bbox instead of the nominal grid.
    ink_box = region.bbox()
    cx = round((ink_box.left + ink_box.right) / 2)
    cy = round((ink_box.bottom + ink_box.top) / 2)
    if cx or cy:
        region.transform(db.Trans(-cx, -cy))
        ink_box = region.bbox()

    # deliberately no .merged() -- dots are meant to stay isolated,
    # distinct shapes (see module docstring)
    cell.shapes(li_m2).insert(region)

    width_um = ink_box.width() * dbu
    height_um = ink_box.height() * dbu
    return ly, cell, width_um, height_um


def self_check(ly: db.Layout, cell: db.Cell) -> tuple[int, int]:
    li_m2 = ly.layer(*M2_LAYER)
    region = db.Region(cell.begin_shapes_rec(li_m2))
    w_viol = region.width_check(int(round(M2_WMIN / ly.dbu)))
    s_viol = region.space_check(int(round(M2_SMIN / ly.dbu)))
    return w_viol.count(), s_viol.count()


def main() -> None:
    if len(sys.argv) < 3:
        print(__doc__.strip().splitlines()[-4])  # usage line
        sys.exit(2)

    png_path = Path(sys.argv[1])
    out_path = Path(sys.argv[2])
    cell_name = sys.argv[3] if len(sys.argv) > 3 else out_path.stem

    if not png_path.exists():
        raise SystemExit(f"input PNG not found: {png_path}")

    ink = load_ink_mask(png_path)
    cols, rows = compute_grid_size(ink)
    grid_on = digitize(ink, cols, rows)

    n_on = int(grid_on.sum())
    print(f"digitized grid: {cols}x{rows} ({n_on} ON cells, "
          f"pitch={PITCH}um, dot={DOT}um, gap={MARGIN * 2:.1f}um)")

    ly, cell, width_um, height_um = build_logo_cell(grid_on, cell_name)
    box = cell.bbox()
    print(f"ink bbox (centered on origin): {width_um:.1f} x {height_um:.1f} um "
          f"(limit {BBOX_X_MAX} x {BBOX_Y_MAX}), "
          f"center=({(box.left + box.right) / 2 * ly.dbu:.3f}, "
          f"{(box.bottom + box.top) / 2 * ly.dbu:.3f})um")

    if width_um > BBOX_X_MAX or height_um > BBOX_Y_MAX:
        raise SystemExit(
            f"logo exceeds bbox: {width_um:.1f}x{height_um:.1f}um "
            f"(limit {BBOX_X_MAX}x{BBOX_Y_MAX})"
        )

    wv, sv = self_check(ly, cell)
    print(f"self-check: width_check(<{M2_WMIN}um) violations={wv}, "
          f"space_check(<{M2_SMIN}um) violations={sv}")

    if wv or sv:
        raise SystemExit(f"logo fails DRC self-check: width={wv}, space={sv}")

    out_path.parent.mkdir(parents=True, exist_ok=True)
    ly.write(str(out_path))
    print(f"wrote {out_path} (cell {cell_name!r})")


if __name__ == "__main__":
    main()
